[package]
name = "pop-cosmic-panel"
version = "0.1.0"
edition = "2018"
license = "LGPL-3.0-or-later"

[dependencies]
cascade = "1"
chrono = "0.4"
byte_string = "1"
derivative = "2"
gdk4-x11 = "0.3"
gdk4-wayland = { version = "0.3", optional = true }
gtk4 = "0.3"
gobject-sys = "0.14.0"
once_cell = "1"
toml = "0.5"
wayland-client = { version = "0.28", optional = true }
wayland-protocols = { version = "0.28", features = [ "client", "unstable_protocols" ], optional = true }
x11 = { version = "2", features = ["xlib"] }
zbus = "1"

[features]
layer-shell = ["gdk4-wayland", "wayland-client", "wayland-protocols"]
