[package]
name = "cosmic-applet-status-area"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0-or-later"

[dependencies]
futures = "0.3"
libcosmic = { git = "https://github.com/pop-os/libcosmic/", branch = "master", default-features = false, features = ["wayland", "applet", "tokio"] }
serde = "1"
tokio = { version = "1.23.0" }
zbus = { version = "3", default-features = false, features = ["tokio"] }
